### PR TITLE
Add the actual event location

### PR DESCRIPTION
**Pull request by iamimmanuelraj**

### CODE REVIEW

**Comment by StarkDroid** [comment]
Holding onto this for now until the venue is confirmed

**Review by navhits — DISMISSED** [review]
It will be better if we can add pictures of the venue.  Please try this

**Review by StarkDroid — APPROVED** [review]
We can go ahead with this for now, I'll make further changes on top of this later

**Comment by navhits** [comment]
@all-contributors add @iamimmanuelraj for content

**Pull request merged**
